DROP TRIGGER IF EXISTS eventos_proyectos ON proyectos;
DROP TRIGGER IF EXISTS eventos_tareas_proyectos ON tareas_proyectos;
DROP TRIGGER IF EXISTS eventos_notas_proyecto ON notas_proyecto;
DROP TRIGGER IF EXISTS eventos_documentos_proyecto ON documentos_proyecto;
DROP TRIGGER IF EXISTS eventos_project_logs ON project_logs;
DROP TRIGGER IF EXISTS eventos_persona ON persona;
DROP TRIGGER IF EXISTS eventos_interacciones ON interacciones;
DROP TRIGGER IF EXISTS eventos_reflexiones ON reflexiones;
DROP TRIGGER IF EXISTS eventos_lista_deseos ON lista_deseos;
DROP TRIGGER IF EXISTS eventos_banco ON banco;
DROP TRIGGER IF EXISTS eventos_grupo_item_finanzas ON grupo_item_finanzas;
DROP TRIGGER IF EXISTS eventos_movimiento_esperado_finanzas ON movimiento_esperado_finanzas;
DROP TRIGGER IF EXISTS eventos_finanzas_plantilla ON finanzas_plantilla;
DROP TRIGGER IF EXISTS fecha_actualizacion_tareas_proyectos ON tareas_proyectos;
DROP TRIGGER IF EXISTS fecha_actualizacion_proyectos ON proyectos;
DROP FUNCTION IF EXISTS registrar_evento();
DROP FUNCTION IF EXISTS tocar_fecha_actualizacion();
DROP TABLE IF EXISTS eventos;
ALTER TABLE tareas_proyectos DROP COLUMN IF EXISTS fecha_actualizacion;
ALTER TABLE proyectos DROP COLUMN IF EXISTS fecha_actualizacion;
